# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-14 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='name',
            field=models.CharField(blank=True, default=b'', max_length=128),
        ),
    ]
