# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-01 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_auto_20211214_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='bookmarkcategory',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
