# Generated by Django 4.2.19 on 2025-12-16 21:12

from django.db import migrations, models


def dedupe_uncategorized_bookmarks(apps, schema_editor):
    Bookmark = apps.get_model('bookmarks', 'Bookmark')
    duplicates = (
        Bookmark.objects
        .filter(category__isnull=True)
        .values('user_id', 'sound_id')
        .annotate(count=models.Count('id'))
        .filter(count__gt=1)
    )

    for duplicate in duplicates:
        ids = list(
            Bookmark.objects
            .filter(
                user_id=duplicate['user_id'],
                sound_id=duplicate['sound_id'],
                category__isnull=True,
            )
            .order_by('id')
            .values_list('id', flat=True)
        )

        ids_to_delete = ids[1:]
        if ids_to_delete:
            Bookmark.objects.filter(id__in=ids_to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0006_alter_bookmark_unique_together'),
    ]

    operations = [
        migrations.RunPython(dedupe_uncategorized_bookmarks, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', True)), fields=('user', 'sound'), name='bookmarks_unique_uncategorized'),
        ),
    ]
