# Generated by Django 1.11.29 on 2022-01-11 12:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geotags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geotag',
            name='information',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='geotag',
            name='should_update_information',
            field=models.BooleanField(default=True),
        ),
    ]
