# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-01 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geotags', '0003_geotag_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geotag',
            name='location_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
