# Generated by Django 3.2.17 on 2023-02-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geotags', '0004_auto_20230201_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geotag',
            name='information',
            field=models.JSONField(null=True),
        ),
    ]
