# Generated by Django 3.2.23 on 2025-02-04 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0052_alter_sound_type'),
        ('geotags', '0006_remove_geotag_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='geotag',
            name='sound2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geotags2', to='sounds.sound'),
        ),
    ]
