# Generated by Django 3.2.23 on 2025-02-04 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0054_remove_sound_base_filename_slug'),
        ('geotags', '0008_geotag_migrate_sound'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geotag',
            old_name='sound2',
            new_name='sound',
        ),
        migrations.AlterField(
            model_name='geotag',
            name='sound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geotags2', to='sounds.sound'),
        ),
    ]
