# Generated by Django 3.2.23 on 2025-02-10 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0055_remove_sound_geotag'),
        ('geotags', '0009_rename_sound2_geotag_sound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geotag',
            name='sound',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geotag', to='sounds.sound'),
        ),
    ]
