volumes:
    pgdata:
    solr9data:

services:
    db:
        image: postgres:12.1
        env_file:
            - environment
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./freesound-data/db_dev_dump:/freesound-data/db_dev_dump
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=freesound
            - POSTGRES_DB=freesound
            - FS_USER_ID

    search:
        image: solr:9.8.1
        command: ["-c"]
        volumes:
            - solr9data:/var/solr
        ports:
            - "8983:8983"

    test_runner:
        build:
            context: ./
            dockerfile: ./docker/Dockerfile.workers_web
        init: true
        volumes:
            - .:/code
            - ./freesound-data/:/freesound-data
        env_file:
            - environment
        environment:
            - FS_USER_ID
        depends_on:
            - db

    test_runner_search:
        build:
            context: ./
            dockerfile: ./docker/Dockerfile.workers_web
        init: true
        volumes:
            - .:/code
            - ./freesound-data/:/freesound-data
        env_file:
            - environment
        environment:
            - FS_USER_ID
        depends_on:
            - db
            - search
