#
# Freesound is (c) MUSIC TECHNOLOGY GROUP, UNIVERSITAT POMPEU FABRA
#
# Freesound is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Freesound is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Authors:
#     See AUTHORS file.
#

from django.test import TestCase
from django.urls import reverse
import mock

'''

{'facet_counts': {'facet_dates': {},
                  'facet_fields': {'bitdepth': ['16',
                                                390,
                                                '24',
                                                221,
                                                '0',
                                                105,
                                                '32',
                                                19,
                                                '4',
                                                1],
                                   'bitrate': ['1411',
                                               153,
                                               '1378',
                                               151,
                                               '2250',
                                               79,
                                               '1500',
                                               32,
                                               '1536',
                                               23],
                                   'channels': ['2',
                                                630,
                                                '1',
                                                91,
                                                '6',
                                                12,
                                                '4',
                                                4],
                                   'grouping_pack': ['9587_Dog Barking Sounds',
                                                     11,
                                                     '7469_Animal Noises',
                                                     10,
                                                     '4026_DOGS everywhere sounds',
                                                     8,
                                                     '4651_villa-maria',
                                                     8,
                                                     '5344_ambiance from south east france_Aubagne',
                                                     8,
                                                     '9915_Animals',
                                                     8,
                                                     '10116_Dog sounds',
                                                     7,
                                                     '8598_DOGS - stereo LR',
                                                     7,
                                                     "690_Dog's Tin Water Bowl",
                                                     6,
                                                     '7887_Amateur Radio',
                                                     6],
                                   'license': ['Attribution',
                                               380,
                                               'Creative Commons 0',
                                               211,
                                               'Attribution Noncommercial',
                                               106,
                                               'Sampling+',
                                               40],
                                   'samplerate': ['44100',
                                                  445,
                                                  '48000',
                                                  210,
                                                  '96000',
                                                  48,
                                                  '11025',
                                                  16,
                                                  '22050',
                                                  10],
                                   'tag': ['dog',
                                           360,
                                           'field-recording',
                                           250,
                                           'barking',
                                           150,
                                           'bark',
                                           148,
                                           'dogs',
                                           134,
                                           'birds',
                                           89,
                                           'animal',
                                           70,
                                           'nature',
                                           62,
                                           'ambiance',
                                           59,
                                           'ambience',
                                           55,
                                           'night',
                                           54,
                                           'wind',
                                           50,
                                           'ambient',
                                           43,
                                           'noise',
                                           43,
                                           'city',
                                           39,
                                           'howl',
                                           33,
                                           'atmosphere',
                                           31,
                                           'water',
                                           31,
                                           'field',
                                           30,
                                           'soundscape',
                                           30,
                                           'people',
                                           26,
                                           'whine',
                                           26,
                                           'summer',
                                           25,
                                           'village',
                                           24,
                                           'general-noise',
                                           23,
                                           'growl',
                                           23,
                                           'rain',
                                           23,
                                           'white-noise',
                                           23,
                                           'background',
                                           22,
                                           'country',
                                           22],
                                   'type': ['wav',
                                            502,
                                            'mp3',
                                            92,
                                            'flac',
                                            76,
                                            'aiff',
                                            31,
                                            'aif',
                                            25],
                                   'username': ['dobroide',
                                                36,
                                                'klankbeeld',
                                                28,
                                                'felix.blume',
                                                17,
                                                'noisecollector',
                                                17,
                                                'acclivity',
                                                12,
                                                'puniho',
                                                12,
                                                'jace',
                                                11,
                                                'unfa',
                                                11,
                                                'erh',
                                                10,
                                                'esperri',
                                                10,
                                                'adamlhumphreys',
                                                9,
                                                'miastodzwiekow',
                                                9,
                                                'robinhood76',
                                                9,
                                                'silencyo',
                                                9,
                                                'conleec',
                                                8,
                                                'rdholder',
                                                8,
                                                'thecityrings',
                                                8,
                                                'qubodup',
                                                7,
                                                'smokum',
                                                7,
                                                'tails1942',
                                                7,
                                                'arnaud coutancier',
                                                6,
                                                'cognito perceptu',
                                                6,
                                                'cydon',
                                                6,
                                                'dariachic',
                                                6,
                                                'gb01',
                                                6,
                                                'hum',
                                                6,
                                                'pierre grandjean',
                                                6,
                                                'benboncan',
                                                5,
                                                'bmoreno',
                                                5,
                                                'csengeri',
                                                5]},
                  'facet_queries': {},
                  'facet_ranges': {}},
 'grouped': {'grouping_pack': {'groups': [{'doclist': {'docs': [{'id': 197074}],
                                                       'numFound': 1,
                                                       'start': 0},
                                           'groupValue': '12541_Dogs'},
                                          {'doclist': {'docs': [{'id': 197073}],
                                                       'numFound': 2,
                                                       'start': 0},
                                           'groupValue': '12540_Dogs '},
                                          {'doclist': {'docs': [{'id': 98262}],
                                                       'numFound': 8,
                                                       'start': 0},
                                           'groupValue': '4026_DOGS everywhere sounds'},
                                          {'doclist': {'docs': [{'id': 199261}],
                                                       'numFound': 7,
                                                       'start': 0},
                                           'groupValue': '8598_DOGS - stereo LR'},
                                          {'doclist': {'docs': [{'id': 72539}],
                                                       'numFound': 3,
                                                       'start': 0},
                                           'groupValue': '4664_barks of my dog'},
                                          {'doclist': {'docs': [{'id': 89213}],
                                                       'numFound': 1,
                                                       'start': 0},
                                           'groupValue': '89213'},
                                          {'doclist': {'docs': [{'id': 155382}],
                                                       'numFound': 2,
                                                       'start': 0},
                                           'groupValue': '9591_Sonic Snaps 2012 Hailuoto'},
                                          {'doclist': {'docs': [{'id': 72724}],
                                                       'numFound': 3,
                                                       'start': 0},
                                           'groupValue': '4671_Dog sounds'},
                                          {'doclist': {'docs': [{'id': 180940}],
                                                       'numFound': 1,
                                                       'start': 0},
                                           'groupValue': '180940'},
                                          {'doclist': {'docs': [{'id': 199919}],
                                                       'numFound': 1,
                                                       'start': 0},
                                           'groupValue': '199919'},
                                          {'doclist': {'docs': [{'id': 191382}],
                                                       'numFound': 1,
                                                       'start': 0},
                                           'groupValue': '191382'},
                                          {'doclist': {'docs': [{'id': 126948}],
                                                       'numFound': 2,
                                                       'start': 0},
                                           'groupValue': '6363_Animal ambience'},
                                          {'doclist': {'docs': [{'id': 142344}],
                                                       'numFound': 1,
                                                       'start': 0},
                                           'groupValue': '142344'},
                                          {'doclist': {'docs': [{'id': 13237}],
                                                       'numFound': 6,
                                                       'start': 0},
                                           'groupValue': "690_Dog's Tin Water Bowl"},
                                          {'doclist': {'docs': [{'id': 155477}],
                                                       'numFound': 1,
                                                       'start': 0},
                                           'groupValue': '155477'}],
                               'matches': 737,
                               'ngroups': 548}},
 'responseHeader': {'QTime': 17,
                    'params': {'f.grouping_pack.facet.limit': '10',
                               'f.license.facet.limit': '10',
                               'f.tag.facet.limit': '30',
                               'f.username.facet.limit': '30',
                               'facet': 'true',
                               'facet.field': ['samplerate',
                                               'grouping_pack',
                                               'username',
                                               'tag',
                                               'bitrate',
                                               'bitdepth',
                                               'type',
                                               'channels',
                                               'license'],
                               'facet.limit': '5',
                               'facet.mincount': '1',
                               'facet.missing': 'false',
                               'facet.sort': 'true',
                               'fl': 'id',
                               'group': 'true',
                               'group.cache.percent': '0',
                               'group.field': 'grouping_pack',
                               'group.format': 'grouped',
                               'group.limit': '1',
                               'group.main': 'false',
                               'group.ngroups': 'true',
                               'group.offset': '0',
                               'group.rows': '10',
                               'group.start': '0',
                               'group.truncate': 'false',
                               'q': 'dogs',
                               'qf': 'id^4 tag^4 description^3 username^1 pack_tokenized^2 original_filename^2',
                               'qt': 'dismax',
                               'rows': '15',
                               'sort': 'score desc',
                               'start': '0',
                               'wt': 'json'},
                    'status': 0}}


'''


class SearchPageTests(TestCase):

    fixtures = ['users', 'sounds_with_tags']

    @mock.patch('utils.search.solr.Solr.select')
    def test_search_page_response_ok(self, solr_select):
        # solr_select.return_value
        # 200 response on sound search page access
        resp = self.client.get(reverse('sounds-search'))
        self.assertEqual(resp.status_code, 200)
