# Generated by Django 1.9.5 on 2016-04-22 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0002_apiv2client_oauth_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiv2client',
            name='scope',
        ),
    ]
