# Generated by Django 1.9.5 on 2016-10-19 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0003_remove_apiv2client_scope'),
    ]

    # This api_apikey table is from apiv1, and was not removed when
    # the api was disabled.
    operations = [
            migrations.RunSQL("drop table if exists api_apikey")
    ]
