# Generated by Django 1.11.20 on 2019-02-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0004_auto_20161019_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiv2client',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
