# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-31 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0005_downloadtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloadtoken',
            old_name='application',
            new_name='client_id',
        ),
    ]
