# Generated by Django 1.11.29 on 2020-12-30 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0005_auto_20190222_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIClientDailyUsageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_requests', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('apiv2_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='apiv2.ApiV2Client')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='apiclientdailyusagehistory',
            unique_together={('apiv2_client', 'date')},
        ),
    ]
