# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-31 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0006_auto_20170131_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadtoken',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiv2.ApiV2Client'),
        ),
    ]
