# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-01 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0007_auto_20170131_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadtoken',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='downloadtoken',
            name='sound',
        ),
        migrations.RemoveField(
            model_name='downloadtoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='DownloadToken',
        ),
    ]
