# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 10:33
from __future__ import unicode_literals

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, default=api.models.generate_key, max_length=32, unique=True)),
                ('status', models.CharField(choices=[(b'OK', b'Approved'), (b'REJ', b'Rejected'), (b'REV', b'Revoked'), (b'PEN', b'Pending')], default=b'OK', max_length=3)),
                ('name', models.CharField(max_length=64)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('accepted_tos', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
