# Generated by Django 1.11 on 2017-06-27 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0007_auto_20161018_1809'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sound',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sounds.Sound'),
        ),
    ]
