# Generated by Django 1.11 on 2017-07-10 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20170627_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='sound',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sounds.Sound'),
        ),
    ]
