# Generated by Django 3.2.17 on 2023-09-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_auto_20230206_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='contains_hyperlink',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
