# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 20:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sounds', '0012_auto_20171002_1710'),
        ('ratings', '0003_copy_sound_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set([('user', 'sound')]),
        ),
    ]
