# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_auto_20171011_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='object_id',
        ),
    ]
