# Generated by Django 1.11.29 on 2023-02-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20171127_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='moderation_state',
            field=models.CharField(choices=[('NM', 'NEEDS_MODERATION'), ('OK', 'OK')], db_index=True, default='OK', max_length=2),
        ),
        migrations.AlterField(
            model_name='thread',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sunk'), (1, 'Regular'), (2, 'Sticky')], db_index=True, default=1),
        ),
    ]
