# Generated by Django 3.2.17 on 2023-09-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20230201_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='order',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
