# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-13 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deleted_user',
            field=models.BooleanField(default=False),
        ),
    ]
