# Generated by Django 1.9.5 on 2016-07-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_deleted_user',
            field=models.BooleanField(default=False),
        ),
    ]
