# Generated by Django 1.9.5 on 2017-03-28 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_profile_is_adult'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPreferenceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('send_by_default', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserEmailSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.EmailPreferenceType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
