# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-29 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_start', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='campaign',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.DonationCampaign'),
            preserve_default=False,
        ),
    ]
