# Generated by Django 1.9.5 on 2017-03-28 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_copy_email_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='enabled_stream_emails',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='wants_newsletter',
        ),
    ]
