# Generated by Django 1.11 on 2017-10-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_donations_reminder_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sound_signature',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
