# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-28 18:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0013_profile_sound_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldUsername',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_usernames', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
