# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20171219_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='num_pack_downloads',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='num_sound_downloads',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
