# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20171129_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldusername',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
