# Generated by Django 1.11 on 2018-07-10 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_gdpracceptance'),
        ('accounts', '0019_emailbounce'),
    ]

    operations = [
    ]
