# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 16:44
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.hashers import make_password


def forwards_func(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    users = User.objects.filter(profile__is_deleted_user=True)
    for user in users:
        # Don't use user.set_unusable_password because the `User` class here is a
        # class made by the migration framework and not our actual User class
        user.password = make_password(None)
        user.save(update_fields=['password'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_emailbounce'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
