# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_gdpracceptance'),
        ('accounts', '0019_emailbounce'),
    ]

    operations = [
    ]
