# Generated by Django 1.11.20 on 2019-02-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_deleted_unusuable_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_attempt_of_sending_stream_email',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_donation_email_sent',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_stream_email_sent',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
