# Generated by Django 1.11 on 2018-07-12 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_merge_20180710_1458'),
        ('accounts', '0020_deleted_unusuable_password'),
    ]

    operations = [
    ]
