# Generated by Django 1.11.20 on 2019-09-27 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_deleteduser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_deleted_user',
            new_name='is_anonymized_user',
        ),
    ]
