# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-10 14:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20191010_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleteduser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 10, 14, 40, 42, 593925)),
            preserve_default=False,
        ),
    ]
