# Generated by Django 1.11.20 on 2019-10-10 14:40

import datetime
from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20191010_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleteduser',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
