# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-16 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20191010_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleteduser',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
