# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-13 11:32
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0030_auto_20191016_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeletionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[(b're', b'Received email deletion request'), (b'wa', b'Waiting for user action'), (b'ca', b'Request was cancelled'), (b'tr', b'Deletion action was triggered'), (b'de', b'User has been deleted or anonymized')], db_index=True, default=b're', max_length=2)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status_history', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('triggered_deletion_action', models.CharField(max_length=100)),
                ('triggered_deletion_reason', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='deleteduser',
            name='sounds_were_also_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdeletionrequest',
            name='deleted_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.DeletedUser'),
        ),
        migrations.AddField(
            model_name='userdeletionrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
