# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-07 14:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0030_auto_20191016_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGDPRDeletionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(max_length=200)),
                ('date_request_received', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[(b're', b'Received'), (b'wa', b'Waiting for user action'), (b'ca', b'Request cancelled'), (b'de', b'User has been deleted')], db_index=True, default=b're', max_length=2)),
                ('deleted_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.DeletedUser')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gdpr_deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
