# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-12 17:42
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0030_auto_20191016_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeletionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(max_length=200)),
                ('date_request_received', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[(b're', b'Received email deletion request'), (b'wa', b'Waiting for user action'), (b'ca', b'Request was cancelled'), (b'de', b'User has been deleted or anonymized')], db_index=True, default=b're', max_length=2)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status_history', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('deleted_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.DeletedUser')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
