# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-10 17:04
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_usergdprdeletionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergdprdeletionrequest',
            name='status_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
