# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-12 07:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0032_auto_20210409_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdeletionrequest',
            old_name='email',
            new_name='email_from',
        ),
        migrations.RemoveField(
            model_name='userdeletionrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userdeletionrequest',
            name='username',
        ),
        migrations.AddField(
            model_name='userdeletionrequest',
            name='user_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_requests_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdeletionrequest',
            name='user_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_requests_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdeletionrequest',
            name='username_from',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userdeletionrequest',
            name='username_to',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
