# Generated by Django 1.11.29 on 2022-03-17 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20210412_1738'),
        ('accounts', '0021_merge_20180712_1536'),
    ]

    operations = [
    ]
