# Generated by Django 1.11.29 on 2023-02-01 11:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_merge_20220317_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleteduser',
            name='reason',
            field=models.CharField(choices=[('sp', 'Spammer'), ('ad', 'Deleted by an admin'), ('sd', 'Self deleted')], max_length=2),
        ),
        migrations.AlterField(
            model_name='emailbounce',
            name='type',
            field=models.CharField(choices=[('UD', 'Undetermined'), ('PE', 'Permanent'), ('TR', 'Transient')], db_index=True, default='UD', max_length=2),
        ),
        migrations.AlterField(
            model_name='emailpreferencetype',
            name='send_by_default',
            field=models.BooleanField(default=True, help_text='Indicates if the user should receive an email, if UserEmailSetting exists for the user then the behavior is the opposite'),
        ),
        migrations.AlterField(
            model_name='gdpracceptance',
            name='date_accepted',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdeletionrequest',
            name='email_from',
            field=models.CharField(help_text='The email from which the user deletion requestwas received.', max_length=200),
        ),
        migrations.AlterField(
            model_name='userdeletionrequest',
            name='status',
            field=models.CharField(choices=[('re', 'Received email deletion request'), ('wa', 'Waiting for user action'), ('ca', 'Request was cancelled'), ('tr', 'Deletion action was triggered'), ('de', 'User has been deleted or anonymized')], db_index=True, default='re', max_length=2),
        ),
        migrations.AlterField(
            model_name='userdeletionrequest',
            name='user_to',
            field=models.ForeignKey(help_text='The user account that should be deleted if this request proceeds. Note that you can click on the magnifying glass icon and search by email.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_requests_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
