# Generated by Django 3.2.17 on 2023-03-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20230206_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allow_simultaneous_playback',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='prefer_spectrograms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='ui_theme_preference',
            field=models.CharField(choices=[('f', 'Follow system default'), ('l', 'Light'), ('d', 'Dark')], default='f', max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='use_compact_mode',
            field=models.BooleanField(default=False),
        ),
    ]
