# Generated by Django 3.2.17 on 2023-03-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20230320_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='num_user_packs_downloads',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_user_sounds_downloads',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
