# Generated by Django 4.2.19 on 2025-05-23 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0041_alter_profile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('preference', models.CharField(choices=[('fr', "My sounds are used following Freesound's recommendations for interpreting Creative Commons licenses in a generative AI training context"), ('o', 'My sounds are used to train open models that are freely available to the public'), ('on', 'My sounds are used to train open models that are freely available to the public and that do not allow a commercial use')], default='fr', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
