# Generated by Django 4.2.27 on 2026-02-20 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0041_alter_profile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('preference', models.CharField(choices=[('freesound-cc-recommendation', "My sounds are used following Freesound's recommendations for interpreting Creative Commons licenses in a generative AI training context"), ('open-models', 'My sounds are used to train open models that are freely available to the public'), ('open-noncommercial-models', 'My sounds are used to train open models that are freely available to the public and that do not allow a commercial use')], default='freesound-cc-recommendation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
