# Generated by Django 4.2.27 on 2026-07-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_aipreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='aipreference',
            name='opt_out_speech',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aipreference',
            name='preference',
            field=models.CharField(choices=[('no-additional-restrictions', 'No additional restrictions'), ('open-models', 'Open Models only'), ('open-noncommercial-models', 'Open Non-Commercial Models only'), ('no-gen-ai', 'No generative AI')], default='no-additional-restrictions'),
        ),
    ]
