# Generated by Django 4.2.27 on 2026-07-10 07:41

from django.db import migrations, models


def rename_aipreference_preferences(apps, schema_editor):
    AIPreference = apps.get_model('accounts', 'AIPreference')

    preference_mapping = {
        'freesound-cc-recommendation': 'no-additional-preferences',
        'open-noncommercial-models': 'noncommercial-open-source-models',
        'open-models': 'open-source-models',
    }

    for old_value, new_value in preference_mapping.items():
        AIPreference.objects.filter(preference=old_value).update(preference=new_value)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_aipreference_opt_out_speech_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aipreference',
            name='preference',
            field=models.CharField(choices=[('no-additional-preferences', 'No additional preferences'), ('open-source-models', 'Open Source Models only'), ('noncommercial-open-source-models', 'Non-Commercial Open Source Models only'), ('no-gen-ai', 'No generative AI')], default='no-additional-preferences'),
        ),
        migrations.RunPython(
            rename_aipreference_preferences,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
