FROM freesound:2023-07-py2

RUN mkdir /code
RUN mkdir /tag_recommendation_models
WORKDIR /code

COPY --chown=fsweb:fsweb requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# To avoid installation problems, csc-pysparse needs to be installed after the other packages in requirements.txt
# have been installed. We might want to replace this package in the future to avoid this "hack".
RUN pip install csc-pysparse==1.1.1.4

COPY --chown=fsweb:fsweb . /code
