FROM python:3.12-slim-bookworm

RUN mkdir /code
RUN mkdir /tag_recommendation_models
WORKDIR /code

COPY --chown=fsweb:fsweb tagrecommendation/requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY --chown=fsweb:fsweb tagrecommendation/ /code
