# This container is used for testing. it install the same things as the web container except for
# essentia and other processing depencies. This is to avoid test runs compiling essentia 
# every time we want to run the tests


FROM freesound:2020-02-py3

# Install specific dependencies needed for processing
RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
		sndfile-programs \
		libsndfile1-dev \
	&& rm -rf /var/lib/apt/lists/*

RUN mkdir /code
RUN mkdir /freesound-data
WORKDIR /code

# Install python dependencies
COPY --chown=fsweb:fsweb requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir -r /code/requirements.txt

# Copy source code
COPY --chown=fsweb:fsweb . /code
