FROM python:3.12-slim-bookworm

RUN mkdir /code
WORKDIR /code

COPY --chown=fsweb:fsweb textencoder/requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY --chown=fsweb:fsweb textencoder/ /code
