FROM ubuntu:16.04

RUN apt-get update && apt-get install -y maven openjdk-8-jdk-headless

RUN mkdir /code

ADD . /code

WORKDIR /code
RUN mvn install
# Run a command in the jetty plugin so that it downloads all of the
# jetty dependencies during build
RUN mvn jetty:help
