# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-07 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_donationsmodalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationsmodalsettings',
            name='never_show_modal_to_uploaders',
            field=models.BooleanField(default=True),
        ),
    ]
