# Generated by Django 1.11 on 2017-07-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_auto_20170710_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationsemailsettings',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
