# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-02 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_donation_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='source',
            field=models.CharField(choices=[('p', 'paypal'), ('s', 'stripe'), ('t', 'transfer')], default='p', max_length=2),
        ),
    ]
