# Generated by Django 4.2.27 on 2026-09-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0013_donationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='request_type',
            field=models.CharField(choices=[('erm', 'Email Reminder Repeat Donation'), ('erq', 'Email Request Many Downloads'), ('dp', 'After Download Popup')], max_length=3),
        ),
    ]
