# Generated by Django 3.2.23 on 2025-02-10 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.db.models import F


def migrate_sound_tags(apps, schema_editor):
    SoundTag = apps.get_model('tags', 'SoundTag')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Sound = apps.get_model('sounds', 'Sound')

    # bulk update in batches of 1000
    all_ids = SoundTag.objects.values_list('id', flat=True)
    for i in range(0, len(all_ids), 1000):
        SoundTag.objects.filter(id__in=all_ids[i:i+1000]).update(sound=F('object_id'))



class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaggedItem',
            new_name='SoundTag',
        ),
        migrations.AddField(
            model_name='soundtag',
            name='sound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sounds.sound'),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=migrate_sound_tags,
        ),
        migrations.AlterField(
            model_name='soundtag',
            name='sound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sounds.sound'),
            preserve_default=False,
        ),
    ]
