# Generated by Django 3.2.23 on 2025-02-10 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0053_sound_tags'),
        ('tags', '0002_rename_taggeditem_soundtag'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='soundtag',
            unique_together={('tag', 'sound_id')},
        ),
        migrations.RemoveField(
            model_name='soundtag',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='soundtag',
            name='object_id',
        ),
    ]
