# Generated by Django 4.2.19 on 2025-11-24 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sounds', '0056_sound_bst_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('description', models.TextField(blank=True)),
                ('num_sounds', models.PositiveIntegerField(default=0)),
                ('num_downloads', models.PositiveIntegerField(default=0)),
                ('public', models.BooleanField(default=False)),
                ('is_default_collection', models.BooleanField(default=False)),
                ('maintainers', models.ManyToManyField(related_name='collection_maintainer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='fscollections.collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_downloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='CollectionSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_sound', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('OK', 'Accepted'), ('RE', 'Refused')], db_index=True, default='PE', max_length=2)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectionsound', to='fscollections.collection')),
                ('sound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sounds.sound')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionDownloadSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_download', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fscollections.collectiondownload')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sounds.license')),
                ('sound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sounds.sound')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='sounds',
            field=models.ManyToManyField(blank=True, related_name='collections', through='fscollections.CollectionSound', to='sounds.sound'),
        ),
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
