# Generated by Django 4.2.19 on 2025-11-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0059_alter_soundsimilarityvector'),
        ('fscollections', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collectionsound',
            unique_together={('sound', 'collection')},
        ),
    ]
