# Generated by Django 3.2.23 on 2025-01-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0052_alter_sound_type'),
        ('fscollections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='sound',
        ),
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='collection',
            name='sounds',
            field=models.ManyToManyField(related_name='collections', to='sounds.Sound'),
        ),
    ]
