# Generated by Django 4.2.19 on 2026-01-21 17:34

import django.contrib.postgres.fields
from django.db import migrations, models


def backfill_featured_sound_ids(apps, schema_editor):
    Collection = apps.get_model("fscollections", "Collection")
    CollectionSound = apps.get_model("fscollections", "CollectionSound")

    for collection in Collection.objects.all().iterator():
        featured_ids = list(
            CollectionSound.objects.filter(collection=collection, featured_sound=True).values_list("sound_id", flat=True)
        )
        if featured_ids:
            Collection.objects.filter(id=collection.id).update(featured_sound_ids=featured_ids)


def reverse_backfill_featured_sound_ids(apps, schema_editor):
    Collection = apps.get_model("fscollections", "Collection")
    CollectionSound = apps.get_model("fscollections", "CollectionSound")

    for collection in Collection.objects.exclude(featured_sound_ids=[]).iterator():
        CollectionSound.objects.filter(collection=collection, sound_id__in=collection.featured_sound_ids).update(
            featured_sound=True
        )


class Migration(migrations.Migration):
    dependencies = [
        ("fscollections", "0002_alter_collectionsound_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="featured_sound_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, default=list, size=250
            ),
        ),
        migrations.RunPython(backfill_featured_sound_ids, reverse_backfill_featured_sound_ids),
        migrations.RemoveField(
            model_name="collectionsound",
            name="featured_sound",
        ),
    ]
