# Generated by Django 4.2.19 on 2026-01-21 17:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fscollections', '0002_alter_collectionsound_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionsound',
            name='featured_sound',
        ),
        migrations.AddField(
            model_name='collection',
            name='featured_sound_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=250),
        ),
    ]
