# Generated by Django 3.2.23 on 2025-01-16 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0052_alter_sound_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fscollections', '0002_auto_20250109_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='author',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='sounds',
        ),
        migrations.AddField(
            model_name='collection',
            name='maintainers',
            field=models.ManyToManyField(related_name='collection_maintainer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collection',
            name='num_sounds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collection',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='CollectionSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('OK', 'OK'), ('DE', 'Deferred')], db_index=True, default='PE', max_length=2)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectionsound', to='fscollections.collection')),
                ('sound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sounds.sound')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
