# Generated by Django 4.2.27 on 2026-07-10 08:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fscollections', '0003_remove_collectionsound_featured_sound_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='featured_sound_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=6),
        ),
    ]
