# Generated by Django 3.2.23 on 2025-02-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fscollections', '0003_auto_20250116_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='collectionsound',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('OK', 'Accepted'), ('RE', 'Refused')], db_index=True, default='PE', max_length=2),
        ),
    ]
