# Generated by Django 3.2.23 on 2025-02-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fscollections', '0004_auto_20250204_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_default_collection',
            field=models.BooleanField(default=False),
        ),
    ]
