# Generated by Django 3.2.23 on 2025-02-13 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fscollections', '0005_collection_is_default_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='num_downloads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='maintainers',
            field=models.ManyToManyField(blank=True, related_name='collection_maintainer', to=settings.AUTH_USER_MODEL),
        ),
    ]
