# Generated by Django 3.2.23 on 2025-03-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fscollections', '0007_collection_featured_sound'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='featured_sound',
        ),
        migrations.AddField(
            model_name='collectionsound',
            name='featured_sound',
            field=models.BooleanField(default=False),
        ),
    ]
