# Generated by Django 3.2.23 on 2025-03-10 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sounds', '0052_alter_sound_type'),
        ('fscollections', '0008_auto_20250305_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='max_num_sounds',
            field=models.PositiveIntegerField(default=250),
        ),
        migrations.CreateModel(
            name='CollectionDownloadSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_download', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fscollections.collectiondownload')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sounds.license')),
                ('sound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sounds.sound')),
            ],
        ),
        migrations.AddField(
            model_name='collectiondownload',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='fscollections.collection'),
        ),
        migrations.AddField(
            model_name='collectiondownload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_downloads', to=settings.AUTH_USER_MODEL),
        ),
    ]
