# Generated by Django 3.2.23 on 2025-03-13 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fscollections', '0009_auto_20250310_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='max_num_sounds',
        ),
    ]
