# Generated by Django 4.2.19 on 2025-03-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0055_remove_sound_geotag'),
        ('fscollections', '0010_remove_collection_max_num_sounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='sounds',
            field=models.ManyToManyField(blank=True, related_name='collections', through='fscollections.CollectionSound', to='sounds.sound'),
        ),
    ]
