# Generated by Django 4.2.27 on 2026-07-22 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackOptOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_id', models.CharField(db_index=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_opt_outs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'experiment_id')},
            },
        ),
    ]
