# Generated by Django 4.2.27 on 2026-10-08 10:00

import django.core.validators
from django.db import migrations, models

BST_LINK = (
    '<a href="https://freesound.org/help/faq/#the-broad-sound-taxonomy" target="_blank" rel="noopener noreferrer">'
    "Broad Sound Taxonomy</a>"
)

EXPERIMENTS = [
    {
        "experiment_id": "category_validation",
        "title": "Validating Sound Categorization in Freesound",
        "description": (
            "You are occasionally shown a short question asking whether a sound has been placed in the correct "
            f"category according to the {BST_LINK}. Your answers will help us evaluate sound categorization on "
            "Freesound and better understand how users perceive sound categories."
        ),
    },
    {
        "experiment_id": "category_filter_feedback",
        "title": "Evaluating Category Filters in Freesound Search",
        "description": (
            f"When you filter search results by a category of the {BST_LINK}, you are occasionally asked, "
            "for each sound in the results, whether it is what you were looking for, and how useful the filter was "
            "overall. Your answers will help us evaluate how well the categories work for finding sounds."
        ),
    },
]


def create_experiments(apps, schema_editor):
    # Create the existing experiments with sample rate 0, so they are off until it is changed in the admin
    FeedbackExperiment = apps.get_model('user_feedback', 'FeedbackExperiment')
    for experiment in EXPERIMENTS:
        FeedbackExperiment.objects.get_or_create(experiment_id=experiment["experiment_id"], defaults=experiment)


class Migration(migrations.Migration):

    dependencies = [
        ('user_feedback', '0002_feedbackoptout'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackExperiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_id', models.CharField(max_length=100, unique=True)),
                ('sample_rate', models.FloatField(default=0.0, help_text='Fraction of the eligible views that show the experiment (0 = off, 1 = every view).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('title', models.CharField(help_text='Name of the study, shown in the information modal.', max_length=200)),
                ('description', models.TextField(help_text='Description of the study, shown in the information modal. It can have HTML links.')),
            ],
        ),
        migrations.RunPython(create_experiments, migrations.RunPython.noop),
    ]
