# Generated by Django 1.9.5 on 2016-09-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0002_auto_20160728_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
