# Generated by Django 1.9.5 on 2016-09-19 09:52

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0003_auto_20160914_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedsound',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
