# Generated by Django 1.9.5 on 2016-09-19 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0003_auto_20160914_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedsound',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2016, 9, 19, 9, 52, 45, 883418)),
            preserve_default=False,
        ),
    ]
