# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-03 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0004_sound_is_explicit'),
        ('sounds', '0004_deletedsound_created'),
    ]

    operations = [
    ]
