# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-18 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0004_deletedsound_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='is_explicit',
            field=models.BooleanField(default=False),
        ),
    ]
