# Generated by Django 1.9.5 on 2016-10-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0005_auto_20161004_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='analysis_state',
            field=models.CharField(choices=[(b'PE', 'Pending'), (b'OK', 'OK'), (b'FA', 'Failed'), (b'SK', 'Skipped'), (b'QU', 'Queued')], db_index=True, default=b'PE', max_length=2),
        ),
    ]
