# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-18 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0005_sound_is_explicit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pack',
            unique_together=set([('user', 'name', 'is_deleted')]),
        ),
    ]
