# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-05 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0012_auto_20171002_1710'),
    ]

    operations = [
        migrations.RunSQL('drop TRIGGER if exists forum_thread_delete ON forum_thread'),
        migrations.RunSQL('drop TRIGGER if exists forum_post_delete ON forum_post'),
        migrations.RunSQL('drop TRIGGER if exists forum_post_insert ON forum_post'),
        migrations.RunSQL('drop TRIGGER if exists forum_thread_insert ON forum_thread'),
        migrations.RunSQL('drop TRIGGER if exists forum_thread_update ON forum_thread'),
        migrations.RunSQL('drop TRIGGER if exists download_post_insert ON sounds_download'),
        migrations.RunSQL('drop TRIGGER if exists download_post_delete ON sounds_download'),
        migrations.RunSQL('drop TRIGGER if exists rating_post_delete ON ratings_rating'),
        migrations.RunSQL('drop TRIGGER if exists rating_post_insert ON ratings_rating'),
        migrations.RunSQL('drop TRIGGER if exists rating_post_update ON ratings_rating')
    ]
