# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-24 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0013_remove_triggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='pack',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='sounds.Pack'),
        ),
        migrations.AlterField(
            model_name='download',
            name='sound',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='sounds.Sound'),
        ),
    ]
