# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-01 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0014_packdownload_packdownloadjson_packdownloadsound'),
        ('sounds', '0015_auto_20171124_1651'),
    ]

    operations = [
    ]
