# Generated by Django 1.11 on 2018-02-09 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0017_auto_20180117_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='pack',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downloads_old_fied', to='sounds.Pack'),
        ),
        migrations.AlterField(
            model_name='packdownload',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='sounds.Pack'),
        ),
    ]
