# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0018_remove_download_pack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packdownload',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='sounds.Pack'),
        ),
    ]
