# Generated by Django 1.11 on 2018-02-09 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0018_auto_20180209_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='download',
            name='pack',
        ),
        migrations.RunSQL('DELETE FROM sounds_download WHERE sound_id IS NULL')
    ]
