# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 15:06
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sounds', '0018_auto_20180209_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUploadProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('progress_type', models.CharField(choices=[(b'N', b'Not Started'), (b'E', b'Error'), (b'F', b'Finished'), (b'S', b'Started'), (b'V', b'Validated')], default=b'N', max_length=1)),
                ('csv_path', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('validation_errors', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('sounds_valid', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
