# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0020_update_download_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sounds.License'),
        ),
        migrations.AlterField(
            model_name='packdownloadsound',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sounds.License'),
        ),
    ]
