# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0022_auto_20180321_1048'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='download',
            index=models.Index(fields=[b'user', b'sound'], name='sounds_down_user_id_cde275_idx'),
        ),
    ]
