# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0019_bulkuploadprogress'),
        ('sounds', '0023_auto_20180322_1129'),
    ]

    operations = [
    ]
