# Generated by Django 1.11 on 2018-05-03 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0023_auto_20180322_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sound_downloads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='packdownload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_downloads', to=settings.AUTH_USER_MODEL),
        ),
    ]
