# Generated by Django 1.11 on 2018-04-04 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0025_bulkuploadprogress_original_csv_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulkuploadprogress',
            old_name='validation_errors',
            new_name='validation_output',
        ),
    ]
