# Generated by Django 1.11 on 2018-04-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0027_auto_20180406_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkuploadprogress',
            name='progress_type',
            field=models.CharField(choices=[(b'N', b'Not yet validated'), (b'F', b'Finished'), (b'S', b'Sounds being described and processed'), (b'V', b'Finished validation.'), (b'C', b'Closed.')], default=b'N', max_length=1),
        ),
    ]
