# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0024_auto_20180503_1326'),
        ('sounds', '0028_auto_20180411_1634'),
    ]

    operations = [
    ]
