# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 16:09
from __future__ import unicode_literals

from django.db import migrations
from django.core.management.sql import emit_post_migrate_signal


def forwards_func(apps, schema_editor):
    # Needed workaround described in https://code.djangoproject.com/ticket/23422#comment:20 and
    # https://code.djangoproject.com/ticket/23422#comment:25 to be able to get correct permission object here

    db_alias = schema_editor.connection.alias
    emit_post_migrate_signal(2, False, db_alias)

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    bulk_uploaders_group = Group.objects.create(name="bulk_uploaders")
    perm = Permission.objects.get(codename="can_describe_in_bulk")
    bulk_uploaders_group.permissions.add(perm)


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0033_auto_20190528_1554'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
