# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-12 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0033_auto_20190528_1554'),
    ]

    operations = [
        migrations.RunSQL("""CREATE INDEX IF NOT EXISTS sounds_sound_greatest_created_mod_date_mod_state_proc_state 
                                       ON sounds_sound (greatest(created, moderation_date), moderation_state, processing_state)""")
    ]
