# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-20 21:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sounds', '0036_sound_uploaded_with_bulk_upload_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.IntegerField(null=True)),
                ('project_name', models.CharField(max_length=255, null=True)),
                ('sound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sounds.Sound')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
