# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-04 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0036_sound_uploaded_with_bulk_upload_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundanalysis',
            name='extractor_version',
            field=models.CharField(db_index=True, default='1.0.0', max_length=255),
            preserve_default=False,
        ),
    ]
