# Generated by Django 1.11.29 on 2021-04-12 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0037_license_short_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedsound',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
