# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-01 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0037_soundanalysis_extractor_version'),
        ('sounds', '0037_license_short_summary'),
    ]

    operations = [
    ]
