# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-12 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0038_merge_20210301_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soundanalysis',
            old_name='extractor',
            new_name='analyzer',
        ),
        migrations.RenameField(
            model_name='soundanalysis',
            old_name='extractor_version',
            new_name='analyzer_version',
        ),
        migrations.AlterUniqueTogether(
            name='soundanalysis',
            unique_together=set([('sound', 'analyzer', 'analyzer_version')]),
        ),
    ]
