# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-07 14:04
from __future__ import unicode_literals

from django.db import migrations


def update_existing_csv_paths(apps, schema_editor):
    BulkUploadProgress = apps.get_model("sounds", "BulkUploadProgress")
    for bu in BulkUploadProgress.objects.all():
        if '/' in bu.csv_filename:
            # If filename contains /, it means it is a path (old path). Remove the path to keep only the filename
            bu.csv_filename = bu.csv_filename.split('/')[-1]
            bu.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0038_auto_20210412_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulkuploadprogress',
            old_name='csv_path',
            new_name='csv_filename',
        ),
        migrations.RunPython(update_existing_csv_paths, migrations.RunPython.noop)
    ]


