# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-09 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0039_auto_20210312_1922'),
        ('sounds', '0039_auto_20210607_1404'),
    ]

    operations = [
    ]
