# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-09 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0040_merge_20210909_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundanalysis',
            name='analysis_status',
            field=models.CharField(choices=[(b'OK', b'Ok'), (b'SK', b'Skipped'), (b'FA', b'Failed')], db_index=True, max_length=2, null=True),
        ),
    ]
