# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-23 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0041_soundanalysis_analysis_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundanalysis',
            name='is_queued',
            field=models.BooleanField(default=False),
        ),
    ]
