# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-09 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0041_soundanalysis_analysis_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soundanalysis',
            old_name='created',
            new_name='last_sent_to_queue',
        ),
        migrations.RemoveField(
            model_name='soundanalysis',
            name='is_queued',
        ),
        migrations.AddField(
            model_name='soundanalysis',
            name='last_analyzer_finished',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='soundanalysis',
            name='analysis_status',
            field=models.CharField(choices=[(b'QU', b'Queued'), (b'OK', b'Ok'), (b'SK', b'Skipped'), (b'FA', b'Failed')], db_index=True, default=b'QU', max_length=2),
        ),
    ]
