# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-04 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0042_soundanalysis_is_queued'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundanalysis',
            name='num_analysis_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='soundanalysis',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='soundanalysis',
            name='analysis_filename',
        ),
        migrations.RemoveField(
            model_name='soundanalysis',
            name='analyzer_version',
        ),
        migrations.AlterUniqueTogether(
            name='soundanalysis',
            unique_together=set([('sound', 'analyzer')]),
        ),
    ]
