# Generated by Django 1.11.29 on 2022-02-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0042_auto_20220209_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundanalysis',
            name='last_sent_to_queue',
            field=models.DateTimeField(),
        ),
    ]
