# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-09 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0043_auto_20220209_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundanalysis',
            name='last_sent_to_queue',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
