# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-09 11:36
from __future__ import unicode_literals


from django.db import models, migrations
from django.conf import settings


def update_existing_ac_analysis_objects(apps, schema_editor):
    SoundAnalysis = apps.get_model("sounds", "SoundAnalysis")
    db_alias = schema_editor.connection.alias

    for sa in SoundAnalysis.objects.using(db_alias).filter(analyzer='AudioCommonsV3'):
        sa.analyzer = settings.AUDIOCOMMONS_ANALYZER_NAME
        sa.last_analyzer_finished = sa.last_sent_to_queue
        if sa.analysis_data:
            updated_analysis_data = {}
            for key, value in list(sa.analysis_data.items()):
                updated_analysis_data['ac_{0}'.format(key)] = value
            sa.analysis_data = updated_analysis_data
        sa.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0043_auto_20220209_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundanalysis',
            name='last_sent_to_queue',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RunPython(update_existing_ac_analysis_objects, migrations.RunPython.noop),
    ]
