# Generated by Django 1.11.29 on 2023-02-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0045_add_new_licenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkuploadprogress',
            name='progress_type',
            field=models.CharField(choices=[('N', 'Not yet validated'), ('F', 'Finished description'), ('S', 'Sounds being described and processed'), ('V', 'Finished validation'), ('C', 'Closed')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='flag',
            name='reason_type',
            field=models.CharField(choices=[('O', 'Offending sound'), ('I', 'Illegal sound'), ('T', 'Other problem')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='sound',
            name='analysis_state',
            field=models.CharField(choices=[('PE', 'Pending'), ('OK', 'OK'), ('FA', 'Failed'), ('SK', 'Skipped'), ('QU', 'Queued')], db_index=True, default='PE', max_length=2),
        ),
        migrations.AlterField(
            model_name='sound',
            name='moderation_state',
            field=models.CharField(choices=[('PE', 'Pending'), ('OK', 'OK'), ('DE', 'Deferred')], db_index=True, default='PE', max_length=2),
        ),
        migrations.AlterField(
            model_name='sound',
            name='processing_ongoing_state',
            field=models.CharField(choices=[('NO', 'None'), ('QU', 'Queued'), ('PR', 'Processing'), ('FI', 'Finished')], db_index=True, default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='sound',
            name='processing_state',
            field=models.CharField(choices=[('PE', 'Pending'), ('OK', 'OK'), ('FA', 'Failed')], db_index=True, default='PE', max_length=2),
        ),
        migrations.AlterField(
            model_name='sound',
            name='similarity_state',
            field=models.CharField(choices=[('PE', 'Pending'), ('OK', 'OK'), ('FA', 'Failed')], db_index=True, default='PE', max_length=2),
        ),
        migrations.AlterField(
            model_name='sound',
            name='type',
            field=models.CharField(choices=[('wav', 'Wave'), ('ogg', 'Ogg Vorbis'), ('aiff', 'AIFF'), ('mp3', 'Mp3'), ('flac', 'Flac'), ('m4a', 'M4a')], db_index=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='soundanalysis',
            name='analysis_status',
            field=models.CharField(choices=[('QU', 'Queued'), ('OK', 'Ok'), ('SK', 'Skipped'), ('FA', 'Failed')], db_index=True, default='QU', max_length=2),
        ),
    ]
