# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-06 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0046_auto_20230201_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packdownload',
            options={'ordering': ('-created',)},
        ),
    ]
