# Generated by Django 3.2.17 on 2023-02-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0047_auto_20230206_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkuploadprogress',
            name='description_output',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='bulkuploadprogress',
            name='validation_output',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='deletedsound',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='soundanalysis',
            name='analysis_data',
            field=models.JSONField(null=True),
        ),
    ]
