# Generated by Django 3.2.17 on 2023-02-13 11:38

from django.db import migrations, models


def add_form_summaries_to_existing_licenses(apps, schema_editor):
    
    def get_summary_for_describe_form(license_name):
        cc0_description = "You let people use your sounds and they can do whatever they want. They don't even need to credit you."
        ccby_description = "You let people use your sounds, for commercial purposes, but they always need to credit you."
        ccbync_description = "You let people use your sounds, but not for commercial purposes. They also always need to credit you."
        if '0' in license_name.lower():
            return cc0_description
        elif 'noncommercial' in license_name.lower():
            return ccby_description
        elif 'attribution' in license_name.lower():
            return ccbync_description
        return None
    
    License = apps.get_model('sounds', 'License')

    for license in License.objects.all():
        if get_summary_for_describe_form(license.name) is not None:
            license.summary_for_describe_form = get_summary_for_describe_form(license.name)
            license.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0048_auto_20230208_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='summary_for_describe_form',
            field=models.TextField(null=True),
        ),
        migrations.RunPython(add_form_summaries_to_existing_licenses, migrations.RunPython.noop),
    ]
