# Generated by Django 3.2.17 on 2023-09-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0049_license_summary_for_describe_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='order',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
