# Generated by Django 3.2.17 on 2023-09-29 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0050_alter_license_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={},
        ),
        migrations.RemoveField(
            model_name='license',
            name='order',
        ),
    ]
