# Generated by Django 3.2.23 on 2025-02-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_rename_taggeditem_soundtag'),
        ('sounds', '0052_alter_sound_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='tags',
            field=models.ManyToManyField(through='tags.SoundTag', to='tags.Tag'),
        ),
    ]
