# Generated by Django 3.2.23 on 2024-12-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0052_alter_sound_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='bst_category',
            field=models.CharField(blank=True, choices=[('m', 'Music'), ('is', 'Instrument samples'), ('sp', 'Speech'), ('fx', 'Sound Effects'), ('ss', 'Soundscapes')], default=None, max_length=8, null=True),
        ),
    ]
