# Generated by Django 4.2.19 on 2025-03-12 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0053_sound_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sound',
            name='base_filename_slug',
        ),
    ]
