# Generated by Django 3.2.23 on 2025-02-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0054_remove_sound_base_filename_slug'),
        ('geotags', '0009_rename_sound2_geotag_sound'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sound',
            name='geotag',
        ),
    ]
