# Generated by Django 3.2.23 on 2025-01-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0054_alter_sound_bst_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='is_gen_ai',
            field=models.BooleanField(default=False),
        ),
    ]
