# Generated by Django 4.2.19 on 2025-06-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0056_sound_bst_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sound',
            name='has_bad_description',
        ),
        migrations.RemoveField(
            model_name='sound',
            name='moderation_note',
        ),
    ]
