# Generated by Django 4.2.19 on 2025-11-07 07:33

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0057_remove_sound_has_bad_description_moderation_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundSimilarityVector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_space_name', models.CharField(max_length=100)),
                ('vector', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('sound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_vectors', to='sounds.sound')),
            ],
        ),
    ]
