# Generated by Django 4.2.19 on 2025-11-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0058_soundsimilarityvector'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='soundsimilarityvector',
            unique_together={('sound', 'similarity_space_name')},
        ),
    ]
