# Generated by Django 4.2.19 on 2025-11-27 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sounds', '0059_alter_soundsimilarityvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingSound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=512)),
                ('path', models.CharField(max_length=1024)),
                ('filesize', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('UP', 'Uploaded'), ('DE', 'Described'), ('DL', 'Deleted')], default='UP', max_length=2)),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sounds.license')),
                ('pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sounds.pack')),
            ],
        ),
        migrations.CreateModel(
            name='PendingSoundAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('processing_state', models.CharField(choices=[('PE', 'Pending'), ('PR', 'Processing'), ('OK', 'OK'), ('FA', 'Failed')], default='PE', max_length=2)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('samplerate', models.FloatField(blank=True, null=True)),
                ('channels', models.IntegerField(blank=True, null=True)),
                ('bitdepth', models.IntegerField(blank=True, null=True)),
                ('md5', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('pending_sound', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='sounds.pendingsound')),
            ],
        ),
        migrations.AddField(
            model_name='pendingsound',
            name='sound',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_sound', to='sounds.sound'),
        ),
        migrations.AddField(
            model_name='pendingsound',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_sounds', to=settings.AUTH_USER_MODEL),
        ),
    ]
