# Generated by Django 4.2.27 on 2026-05-07 16:05

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('sounds', '0060_alter_sound_bst_category'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='sound',
            index=models.Index(condition=models.Q(('is_index_dirty', True)), fields=['is_index_dirty'], name='sound_is_index_dirty_partial'),
        ),
    ]
