# Generated by Django 4.2.27 on 2026-09-21 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0008_rename_allow_oauth_passoword_grant_apiv2client_allow_oauth_password_grant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sounds', '0061_sound_sound_is_index_dirty_partial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackDownloadAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('api_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv2.apiv2client')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads_api', to='sounds.pack')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='PackDownloadSoundAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sounds.license')),
                ('pack_download_api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sounds.packdownloadapi')),
                ('sound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sounds.sound')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('api_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv2.apiv2client')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sounds.license')),
                ('sound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads_api', to='sounds.sound')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
                'indexes': [models.Index(fields=['api_client', 'sound'], name='sounds_down_api_cli_ce555a_idx')],
            },
        ),
    ]
