# Generated by Django 4.2.27 on 2026-10-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0062_packdownloadapi_packdownloadsoundapi_downloadapi'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pack',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='pack',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('user', 'name'), name='unique_active_pack_name_per_user'),
        ),
    ]
