# Generated by Django 4.2.27 on 2026-09-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='query_type',
            field=models.CharField(choices=[('sp', 'Search Page'), ('tp', 'Tags Page'), ('api', 'Api')], default='sp', max_length=3),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
