# Generated by Django 1.9.5 on 2016-06-08 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0001_initial'),
        ('tickets', '0002_auto_20160505_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sound',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sounds.Sound'),
        ),
    ]
