# Generated by Django 1.9.5 on 2016-06-08 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_copy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedcontent',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='content',
        ),
        migrations.DeleteModel(
            name='LinkedContent',
        ),
    ]
