# Generated by Django 1.11 on 2017-06-26 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0006_remove_ticket_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='comment_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_commenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commented_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
