# Generated by Django 4.2.19 on 2025-03-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20230206_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='queue',
        ),
        migrations.DeleteModel(
            name='Queue',
        ),
    ]
