# Generated by Django 4.2.19 on 2025-06-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_remove_ticket_queue_delete_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='userannotation',
            name='created',
            field=models.DateTimeField(null=True, default=None),
        ),
        migrations.AlterField(
            model_name='userannotation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userannotation',
            name='automated',
            field=models.BooleanField(default=False),
        ),
    ]
