name: Flake8
# https://gitlab.com/pycqa/flake8

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Lint with flake8
        run: |
          pip -q install -r requirements.linters.txt
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # These are just the style issues
          flake8 . --count --statistics